### ISSUE TITLE
google maps api for android 2.0 support

### ISSUE THREAD

**Issue by jnozsc** [Vizzuality/cartodb-android-example#1]
google maps api for android 1.0 has been deprecated 

```
Note: Version 1 of the Google Maps Android API has been officially deprecated as of December 3rd, 2012. This means that from March 18th, 2013 you will no longer be able to request an API key for this version. No new features will be added to Google Maps Android API v1. However, apps using v1 will continue to work on devices. Existing and new developers are encouraged to use Google Maps Android API v2.
```

**Comment by jnozsc** [comment]
After adding jars into the class path, error messages disappears excepts some message as "com.gooogle" etc.
I assume this should be something with google maps api for android.

I will keep investigating this issue.

**Comment by jnozsc** [comment]
After some investigation, I think there is no **MapActivity** or **ItemizedOverlay** or their alternative Class in v2 API, as a result, it seems this project has to be rewritten. 

I notice CartoDB's blog mentioned another API from Nutiteq http://blog.cartodb.com/post/52866435750/guest-post-cartodb-goes-native-mobile-interactive-with Is it still maintained by any team?  I tried that example. It does not work either for me. I also post question, which has not been solved yet, to their mail list.

**Comment by javisantana** [comment]
I don't know if still maintained. 

In any case this example should be easy to port, the cartodb part should be the same
