### ISSUE TITLE
java.lang.NoClassDefFoundError:com.cartodb.impl.CartoDBClient

### ISSUE THREAD

**Issue by jnozsc** [Vizzuality/cartodb-android-example#2]
When I import this project into eclipse with the latest version of Android SDK.

After building, it shows this following error.

``` java
java.lang.NoClassDefFoundError:com.cartodb.impl.CartoDBClient
```

Does this project work well now? Do I miss some configuration?

Thanks!

**Comment by javisantana** [comment]
did you add jars inside lib path to the class path?

**Comment by jnozsc** [comment]
Thanks, after adding these jars, this error message disappear.
